### ISSUE TITLE
Как увеличить радиус показа покемонов

### ISSUE THREAD

**Issue by MediaRise** [hflabs/pokemon#1]
Дорогие разработчики, подскажите пожалуйста, как увеличить радиус показа покемонов?

**Comment by nalgeon** [comment]
Увеличить значение `STEP_LIMIT` в `server/settings.py` .

**Comment by MediaRise** [comment]
Спасибо большое за ответ!, но чем больше значение, менее стабильнее будет работать сервер?

**Comment by nalgeon** [comment]
Чем больше значение, тем дольше будет отрабатывать радар. И выше вероятность словить таймаут от серверов Ниантика. Так что и стабильность ниже.

**Comment by MediaRise** [comment]
Спасибо вам большое за ответ!
